# Default values for site.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: "dev"
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
