apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "site.fullname" . }}
  labels:
    {{- include "site.labels" . | nindent 4 }}
data:
  index.html: |-
    {{ .Files.Get "index.html" | nindent 4 }}